title: Boatswain Docs
description: "<a href='https://redsailtechnologies.github.io/boatswain/'>Home</a>  <a href='https://redsailtechnologies.github.io/boatswain/installation.html'>Installation</a>   <a href='https://redsailtechnologies.github.io/boatswain/templates.html'>Templates</a>  <a href='https://redsailtechnologies.github.io/boatswain/api.html'>API</a>"
show_downloads: false
google_analytics:
theme: jekyll-theme-slate